name: Challenge1
 
on:
  workflow_dispatch:
 
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: |
          date
          pwd
          echo "Directory Contents:"
          ls -al
 
  job2:
    name: job2
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python --version
       
 
      - name: set up pandas
        run: pip install pandas

      - name: create artifact
        run: | 
            touch artifact.py
            echo "#this is my python Artifact" >artifact.py
            python artifact.py
