name: tutorial1
on: push

jobs:
    job1:
        name: job1
        runs-on: ubuntu-latest
        steps:
        - name: step1
          run: |
                echo "Hello from job1"
                echo "Today's date is: $(date)"
    
    job2:
        name: job2
        runs-on: windows-latest
        steps:
        - name: step2
          run: |
              echo "hello from job 2"
              echo "Today's date is: $(date)"
    job3:
        runs-on: ubuntu-latest
        steps:
        - name: step 3
          run: |
              echo "hello from job 3"
              echo "Today's date is: $(date)"
          
    job4:
        name: job4
        runs-on: ubuntu-latest
        steps:
        - name: step 4
          run: |
              echo "I am job 4"